{
  testConstraintMessageCode(getConstraint("{val,obj -> return ['test.message', 'arg', 123L]}"),"test","testClass.testString.test.message",new Object[]{"testString",TestClass.class,"test","arg",123L});
  try {
    testConstraintFailed(getConstraint("{val,obj -> return [123L,'arg1','arg2']}"),"test");
    fail("Validator constraint must throw an exception about wrong closure return");
  }
 catch (  IllegalArgumentException iae) {
  }
}
